// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase config
  // Get these values from Firebase Console -> Project Settings -> Your apps
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD2sRrJGl2WkikLLNsf67GymzuyKd1jDuY",
    authDomain: "mindmate-6b273.firebaseapp.com",
    projectId: "mindmate-6b273",
    storageBucket: "mindmate-6b273.firebasestorage.app",
    messagingSenderId: "773902893944",
    appId: "1:773902893944:web:42999f63cef7b34c9dfe8d",
    measurementId: "G-J87XMEP0QV",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sRrJGl2WkikLLNsf67GymzuyKd1jDuY',
    appId: '1:773902893944:android:1c81d75468f374c69dfe8d',
    messagingSenderId: '773902893944',
    projectId: "mindmate-6b273",
    storageBucket: "mindmate-6b273.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMO_KEY_REPLACE_ME',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.moodmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMO_KEY_REPLACE_ME',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.moodmate',
  );
}
